# Generated by Django 5.0 on 2024-01-18 03:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email_address', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='expenses_tracker/static/expenses_tracker/images/')),
                ('occupation', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")])),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('housing', 'Housing'), ('transportation', 'Transportation'), ('groceries', 'Groceries'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('debt_repayment', 'Debt Repayment'), ('entertainment', 'Entertainment'), ('personal_care', 'Personal Care'), ('education', 'Education'), ('insurance', 'Insurance'), ('taxes', 'Taxes'), ('savings', 'Savings'), ('miscellaneous', 'Miscellaneous'), ('travel', 'Travel'), ('home_maintenance', 'Home Maintenance')], max_length=20)),
                ('amount', models.FloatField()),
                ('description', models.TextField(max_length=400, null=True)),
                ('recurring_transaction', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True)),
                ('transaction_title', models.CharField(max_length=50, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='expenses_tracker.user')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('housing', 'Housing'), ('transportation', 'Transportation'), ('groceries', 'Groceries'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('debt_repayment', 'Debt Repayment'), ('entertainment', 'Entertainment'), ('personal_care', 'Personal Care'), ('education', 'Education'), ('insurance', 'Insurance'), ('savings', 'Savings'), ('miscellaneous', 'Miscellaneous'), ('travel', 'Travel'), ('home_maintenance', 'Home Maintenance'), ('investments', 'Investments'), ('taxes', 'Taxes'), ('clothing', 'Clothing'), ('dining_out', 'Dining Out'), ('fitness', 'Fitness')], max_length=20)),
                ('amount', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='expenses_tracker.user')),
            ],
        ),
    ]
