# Generated by Django 5.0 on 2024-01-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0002_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='next_occurrence',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='frequency',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
