# Generated by Django 5.0 on 2024-01-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0004_alter_budget_category_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Groceries', 'Groceries'), ('Utilities', 'Utilities'), ('Healthcare', 'Healthcare'), ('Debt Repayment', 'Debt Repayment'), ('Entertainment', 'Entertainment'), ('Personal Care', 'Personal Care'), ('Education', 'Education'), ('Insurance', 'Insurance'), ('Taxes', 'Taxes'), ('Savings', 'Savings'), ('Miscellaneous', 'Miscellaneous'), ('Travel', 'Travel'), ('Home Maintenance', 'Home Maintenance'), ('Investments', 'Investments'), ('Clothing', 'Clothing'), ('Dining Out', 'Dining Out'), ('Fitness', 'Fitness')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
