# Generated by Django 5.0 on 2024-01-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0008_alter_budget_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
