# Generated by Django 5.0 on 2024-02-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0009_budget_expiration_date_alter_budget_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('General Expenses', 'General Expenses'), ('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Groceries', 'Groceries'), ('Utilities', 'Utilities'), ('Healthcare', 'Healthcare'), ('Debt Repayment', 'Debt Repayment'), ('Entertainment', 'Entertainment'), ('Personal Care', 'Personal Care'), ('Education', 'Education'), ('Insurance', 'Insurance'), ('Savings', 'Savings'), ('Miscellaneous', 'Miscellaneous'), ('Travel', 'Travel'), ('Home Maintenance', 'Home Maintenance'), ('Investments', 'Investments'), ('Taxes', 'Taxes'), ('Clothing', 'Clothing'), ('Dining Out', 'Dining Out'), ('Fitness', 'Fitness'), ('Food', 'Food')], max_length=20),
        ),
    ]
