# Generated by Django 5.0 on 2024-02-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0010_budget_budget_alter_budget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='spent',
            field=models.FloatField(null=True),
        ),
    ]
