# Generated by Django 5.0 on 2024-02-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0011_budget_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='durational',
        ),
    ]
