# Generated by Django 5.0 on 2024-02-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0012_remove_budget_durational'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
