# Generated by Django 5.0 on 2024-02-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0014_alter_budget_category_alter_budget_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='spent',
            field=models.FloatField(default=0.0),
        ),
    ]
