# Generated by Django 5.0 on 2024-02-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0015_alter_budget_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='next_occurrence',
            field=models.DateTimeField(null=True),
        ),
    ]
