# Generated by Django 5.0 on 2024-02-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0017_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_title',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
