# Generated by Django 5.0 on 2024-03-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0019_budget_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('$', 'Dollar - USD'), ('€', 'Euro - EUR'), ('£', 'Pound Sterling - GBP'), ('¥', 'Yen - JPY'), ('₣', 'Franc - CHF'), ('₹', 'Rupee - INR'), ('₦', 'Naira - NGN'), ('د.ك', 'Dinar - KWD'), ('د.إ', 'Dirham - AED'), ('﷼\u200e', 'Riyal - SAR'), ('₻', 'Mark - DEM'), ('₽', 'Ruouble - RUB'), ('₾', 'Lari - GEL'), ('₺', 'Lira - TRY'), ('₼', 'Manat - AZN'), ('₸', 'Tenge - KZT'), ('₴', 'Hryvnia - UAH'), ('₷', 'Spesmilo - XDR'), ('฿', 'Baht - THB'), ('원', 'Won - KRW'), ('₫', 'Dong - VND'), ('₮', 'Tugrik - MNT'), ('₯', 'Drachma - GRD'), ('₱', 'Peso - PHP'), ('₳', 'Austral - AUD'), ('₵', 'Cedi - GHS'), ('₲', 'Guarani - PYG'), ('₪', 'Sheqel - ILS'), ('₰', 'Penny - GBP')], max_length=20, null=True),
        ),
    ]
