# Generated by Django 5.0.2 on 2024-03-05 03:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0020_user_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('$', 'Dollar - USD'), ('€', 'Euro - EUR'), ('£', 'Pound Sterling - GBP'), ('¥', 'Yen - JPY'), ('₣', 'Franc - CHF'), ('₹', 'Rupee - INR'), ('₦', 'Naira - NGN'), ('د.ك', 'Dinar - KWD'), ('د.إ', 'Dirham - AED'), ('﷼\u200e', 'Riyal - SAR'), ('₻', 'Mark - DEM'), ('₽', 'Ruouble - RUB'), ('₾', 'Lari - GEL'), ('₺', 'Lira - TRY'), ('₼', 'Manat - AZN'), ('₸', 'Tenge - KZT'), ('₴', 'Hryvnia - UAH'), ('₷', 'Spesmilo - XDR'), ('฿', 'Baht - THB'), ('원', 'Won - KRW'), ('₫', 'Dong - VND'), ('₮', 'Tugrik - MNT'), ('₯', 'Drachma - GRD'), ('₱', 'Peso - PHP'), ('₳', 'Austral - AUD'), ('₵', 'Cedi - GHS'), ('₲', 'Guarani - PYG'), ('₪', 'Sheqel - ILS'), ('₰', 'Penny - GBP')], max_length=20, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('occupation', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")])),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
