# Generated by Django 5.0.2 on 2024-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0021_alter_budget_user_alter_transaction_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
