# Generated by Django 5.0.3 on 2024-03-21 00:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0025_alter_budget_category_alter_transaction_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('salary or wages', 'Salary or Wages'), ('business income', 'Business Income'), ('rental income', 'Rental Income'), ('investment income', 'Investment Income'), ('interest income', 'Interest Income'), ('pension or retirement income', 'Pension or Retirement Income'), ('social security benefits', 'Social Security Benefits'), ('alimony or child support', 'Alimony or Child Support'), ('royalties', 'Royalties'), ('gifts or inheritance', 'Gifts or Inheritance')], max_length=40)),
                ('amount', models.FloatField()),
                ('notes', models.TextField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
