# Generated by Django 5.0.3 on 2024-03-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0030_rename_source_income_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='income_title',
            new_name='transaction_title',
        ),
    ]
