# Generated by Django 5.0.3 on 2024-03-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0031_rename_income_title_income_transaction_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='recurring_income',
            new_name='recurring_transaction',
        ),
    ]
