# Generated by Django 5.0.3 on 2024-03-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0035_alter_budget_category_alter_budget_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('All Transactions', 'Budget for All Transactions'), ('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Accommodation', 'Accommodation'), ('Groceries', 'Groceries'), ('Utilities', 'Utilities'), ('Healthcare', 'Healthcare'), ('Debt Repayment', 'Debt Repayment'), ('Entertainment', 'Entertainment'), ('Personal Care', 'Personal Care'), ('Education', 'Education'), ('Insurance', 'Insurance'), ('Savings', 'Savings'), ('Miscellaneous', 'Miscellaneous'), ('Travel', 'Travel'), ('Home Maintenance', 'Home Maintenance'), ('Investments', 'Investments'), ('Taxes', 'Taxes'), ('Clothing', 'Clothing'), ('Dining Out', 'Dining Out'), ('Fitness', 'Fitness'), ('Food', 'Food'), ('Business', 'Business'), ('My Girl', 'My Girl'), ('Family', 'Family')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Groceries', 'Groceries'), ('Utilities', 'Utilities'), ('Healthcare', 'Healthcare'), ('Accommodation', 'Accommodation'), ('Debt Repayment', 'Debt Repayment'), ('Entertainment', 'Entertainment'), ('Personal Care', 'Personal Care'), ('Education', 'Education'), ('Insurance', 'Insurance'), ('Taxes', 'Taxes'), ('Savings', 'Savings'), ('Miscellaneous', 'Miscellaneous'), ('Travel', 'Travel'), ('Home Maintenance', 'Home Maintenance'), ('Investments', 'Investments'), ('Clothing', 'Clothing'), ('Dining Out', 'Dining Out'), ('Fitness', 'Fitness'), ('Food', 'Food'), ('Business', 'Business'), ('My Girl', 'My Girl'), ('Family', 'Family'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='frequency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='next_occurrence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
