# Generated by Django 5.0.3 on 2024-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0036_alter_budget_category_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_all_trans_bud',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
