# Generated by Django 5.0.3 on 2024-03-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0037_budget_is_all_trans_bud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='is_all_trans_bud',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_all_trans_bud',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
